import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useToast } from '../contexts/ToastContext';
import {
  History as HistoryIcon, Search, Filter, RefreshCw,
  Battery, Activity, AlertTriangle, CheckCircle,
  Calendar, Clock, ChevronDown, ChevronUp,
  TrendingUp, TrendingDown, Zap, BarChart2,
  Eye, Trash2, Download, X, SlidersHorizontal
} from 'lucide-react';
import Sidebar from '../components/User/UserSidebar';
import api from '../services/api';

// ─────────────────────────────────────────────────────────────
//  Helpers
// ─────────────────────────────────────────────────────────────
function getHealthStatus(soh) {
  if (soh >= 90) return { label: 'Healthy',  color: 'text-green-400',  bg: 'bg-green-500/15',  border: 'border-green-500/25',  dot: 'bg-green-400',  bar: 'bg-green-400'  };
  if (soh >= 75) return { label: 'Moderate', color: 'text-yellow-400', bg: 'bg-yellow-500/15', border: 'border-yellow-500/25', dot: 'bg-yellow-400', bar: 'bg-yellow-400' };
  return               { label: 'Critical',  color: 'text-red-400',    bg: 'bg-red-500/15',    border: 'border-red-500/25',    dot: 'bg-red-400',    bar: 'bg-red-400'    };
}

function formatDate(dateStr) {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleDateString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric'
  });
}

function formatDateTime(dateStr) {
  if (!dateStr) return '—';
  return new Date(dateStr).toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit'
  });
}

function getTimeAgo(dateStr) {
  if (!dateStr) return '—';
  const diff = Date.now() - new Date(dateStr).getTime();
  const m    = Math.floor(diff / 60000);
  if (m < 1)  return 'Just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  if (d < 30) return `${d}d ago`;
  return formatDate(dateStr);
}

const MODEL_LABELS = {
  random_forest:    '🌲 Random Forest',
  svr:              '📐 SVR',
  naive_bayes:      '📊 Naive Bayes',
  gru_randomforest: '🔀 GRU + RF',
  lstm_transformer: '🤖 LSTM',
};

// ─────────────────────────────────────────────────────────────
//  Sub-components
// ─────────────────────────────────────────────────────────────
function StatPill({ icon: Icon, label, value, color }) {
  return (
    <div className="flex items-center gap-2 bg-white/5 border border-white/10 rounded-xl px-4 py-2.5">
      <Icon size={14} className={color} />
      <span className="text-gray-400 text-xs">{label}</span>
      <span className={`font-bold text-sm ${color}`}>{value}</span>
    </div>
  );
}

function LoadingSkeleton() {
  return (
    <div className="animate-pulse space-y-3">
      {[...Array(6)].map((_, i) => (
        <div key={i} className="bg-white/5 rounded-2xl h-20" />
      ))}
    </div>
  );
}

function DetailModal({ log, onClose }) {
  if (!log) return null;
  const soh    = parseFloat(log.soh_predicted) || 0;
  const rul    = parseFloat(log.rul_predicted)  || 0;
  const status = getHealthStatus(soh);

  const handleDownload = () => {
    const content = `
VOLTIQ — BATTERY PREDICTION HISTORY
=====================================
Report Name   : ${log.report_name || '—'}
Battery ID    : ${log.battery_id  || '—'}
Model Used    : ${MODEL_LABELS[log.report_type] || log.report_type || '—'}
Date          : ${formatDateTime(log.created_at)}

PREDICTION RESULTS
=====================================
State of Health (SOH) : ${soh.toFixed(2)}%
Remaining Useful Life : ${rul.toFixed(0)} cycles
Health Status         : ${log.health_status || status.label}

SENSOR INPUT DATA
=====================================
Voltage       : ${log.voltage      ?? '—'} V
Current       : ${log.current_a    ?? '—'} A
Temperature   : ${log.temperature  ?? '—'} °C
Cycle Count   : ${log.cycle_count  ?? '—'}
Capacity      : ${log.capacity     ?? '—'} Ah

Generated by VoltIQ AI System — NASA CALCE Dataset
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url;
    a.download = `${log.report_name || 'history_log'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/75 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-[#0d1628] border border-white/10 rounded-2xl w-full max-w-lg overflow-hidden">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10">
          <div>
            <h3 className="font-bold text-white">{log.report_name || 'History Detail'}</h3>
            <p className="text-gray-500 text-xs mt-0.5">{formatDateTime(log.created_at)}</p>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white transition">
            <X size={20} />
          </button>
        </div>

        {/* SOH + RUL */}
        <div className="grid grid-cols-2 gap-4 p-6 pb-0">
          <div className={`rounded-2xl p-5 text-center border ${status.bg} ${status.border}`}>
            <p className="text-gray-400 text-xs mb-1">State of Health</p>
            <p className={`text-4xl font-black ${status.color}`}>{soh.toFixed(1)}%</p>
            <div className="w-full bg-white/10 rounded-full h-1.5 mt-3">
              <div className={`h-1.5 rounded-full ${status.bar}`} style={{ width: `${Math.min(soh, 100)}%` }} />
            </div>
            <span className={`inline-block mt-2 px-3 py-0.5 rounded-full text-[10px] font-bold uppercase ${status.bg} ${status.color} border ${status.border}`}>
              {log.health_status || status.label}
            </span>
          </div>
          <div className="bg-cyan-500/10 border border-cyan-500/20 rounded-2xl p-5 text-center">
            <p className="text-gray-400 text-xs mb-1">Remaining Life</p>
            <p className="text-4xl font-black text-cyan-400">{Math.round(rul)}</p>
            <p className="text-cyan-600 text-xs mt-1">cycles</p>
            <span className="inline-block mt-2 px-3 py-0.5 rounded-full text-[10px] font-bold bg-cyan-500/15 text-cyan-400 border border-cyan-500/25 uppercase">
              {MODEL_LABELS[log.report_type] || log.report_type || 'Unknown'}
            </span>
          </div>
        </div>

        {/* Sensor Data */}
        <div className="px-6 py-4">
          <p className="text-gray-500 text-[10px] uppercase font-bold tracking-wider mb-3">Sensor Input Data</p>
          <div className="grid grid-cols-3 gap-2">
            {[
              { label: 'Voltage',     value: log.voltage     != null ? `${log.voltage} V`    : '—' },
              { label: 'Current',     value: log.current_a   != null ? `${log.current_a} A`  : '—' },
              { label: 'Temperature', value: log.temperature != null ? `${log.temperature}°C`: '—' },
              { label: 'Cycle Count', value: log.cycle_count != null ? `${log.cycle_count}`  : '—' },
              { label: 'Capacity',    value: log.capacity    != null ? `${log.capacity} Ah`  : '—' },
              { label: 'Battery ID',  value: log.battery_id  || '—' },
            ].map(({ label, value }) => (
              <div key={label} className="bg-white/5 rounded-xl p-3 text-center">
                <p className="text-gray-600 text-[9px] uppercase mb-1">{label}</p>
                <p className="text-white text-xs font-semibold">{value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="flex gap-3 px-6 py-4 border-t border-white/10">
          <button
            onClick={handleDownload}
            className="flex-1 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-emerald-500 text-black font-bold text-sm hover:brightness-110 transition flex items-center justify-center gap-2"
          >
            <Download size={15} /> Download
          </button>
          <button
            onClick={onClose}
            className="flex-1 py-3 rounded-xl border border-white/10 text-gray-400 hover:bg-white/5 transition text-sm"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
//  Main History Page
// ─────────────────────────────────────────────────────────────
export default function HistoryPage() {
  const [logs,        setLogs]        = useState([]);
  const [loading,     setLoading]     = useState(true);
  const [error,       setError]       = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterModel, setFilterModel] = useState('all');
  const [filterHealth,setFilterHealth]= useState('all');
  const [sortBy,      setSortBy]      = useState('date_desc');
  const [showFilters, setShowFilters] = useState(false);
  const [selectedLog, setSelectedLog] = useState(null);
  const [currentPage, setCurrentPage] = useState(1);

  const { addToast } = useToast();
  const navigate     = useNavigate();
  const ITEMS_PER_PAGE = 8;

  const fetchHistory = async () => {
    setLoading(true);
    try {
      const res  = await api.get('/api/reports/');
      const data = res.data?.reports || [];
      setLogs(data);
      setError(null);
    } catch (err) {
      const message = err.response?.data?.detail || 'Failed to load history';
      setError(message);
      addToast(message, 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchHistory(); }, []);

  // ── Filter + Search + Sort ─────────────────────────────────
  const processed = logs
    .filter(log => {
      const soh = parseFloat(log.soh_predicted) || 0;
      const q   = searchQuery.toLowerCase();

      const matchSearch =
        (log.report_name ?? '').toLowerCase().includes(q) ||
        (log.battery_id  ?? '').toLowerCase().includes(q) ||
        (log.report_type ?? '').toLowerCase().includes(q);

      const matchModel = filterModel === 'all' || log.report_type === filterModel;

      const matchHealth =
        filterHealth === 'all'      ? true :
        filterHealth === 'healthy'  ? soh >= 90 :
        filterHealth === 'moderate' ? soh >= 75 && soh < 90 :
        filterHealth === 'critical' ? soh < 75 : true;

      return matchSearch && matchModel && matchHealth;
    })
    .sort((a, b) => {
      switch (sortBy) {
        case 'date_desc': return new Date(b.created_at) - new Date(a.created_at);
        case 'date_asc':  return new Date(a.created_at) - new Date(b.created_at);
        case 'soh_desc':  return (parseFloat(b.soh_predicted) || 0) - (parseFloat(a.soh_predicted) || 0);
        case 'soh_asc':   return (parseFloat(a.soh_predicted) || 0) - (parseFloat(b.soh_predicted) || 0);
        case 'rul_desc':  return (parseFloat(b.rul_predicted) || 0) - (parseFloat(a.rul_predicted) || 0);
        default:          return 0;
      }
    });

  // ── Pagination ─────────────────────────────────────────────
  const totalPages  = Math.ceil(processed.length / ITEMS_PER_PAGE);
  const paginated   = processed.slice(
    (currentPage - 1) * ITEMS_PER_PAGE,
    currentPage * ITEMS_PER_PAGE
  );

  // Reset page on filter change
  useEffect(() => { setCurrentPage(1); }, [searchQuery, filterModel, filterHealth, sortBy]);

  // ── Summary stats ──────────────────────────────────────────
  const totalCount    = logs.length;
  const healthyCount  = logs.filter(l => (parseFloat(l.soh_predicted) || 0) >= 90).length;
  const moderateCount = logs.filter(l => { const s = parseFloat(l.soh_predicted) || 0; return s >= 75 && s < 90; }).length;
  const criticalCount = logs.filter(l => (parseFloat(l.soh_predicted) || 100) < 75).length;
  const avgSoh        = totalCount
    ? (logs.reduce((s, l) => s + (parseFloat(l.soh_predicted) || 0), 0) / totalCount).toFixed(1)
    : null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#050816] via-[#0b1120] to-[#0f172a] text-white flex">
      <Sidebar />

      <main className="flex-1 p-6 lg:p-8 overflow-auto space-y-6">

        {/* ── Header ── */}
        <div className="flex items-start justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-3xl font-bold flex items-center gap-3">
              <HistoryIcon size={28} className="text-cyan-400" />
              Prediction History
            </h1>
            <p className="text-gray-400 text-sm mt-1">
              All battery health predictions — {totalCount} total records
            </p>
          </div>
          <button
            onClick={fetchHistory}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2.5 bg-white/5 border border-white/10 text-gray-400 rounded-xl hover:bg-white/10 transition text-sm disabled:opacity-50"
          >
            <RefreshCw size={15} className={loading ? 'animate-spin' : ''} />
            Refresh
          </button>
        </div>

        {/* ── Summary Stats ── */}
        <div className="flex flex-wrap gap-3">
          <StatPill icon={BarChart2}     label="Total"    value={totalCount}   color="text-cyan-400"   />
          <StatPill icon={CheckCircle}   label="Healthy"  value={healthyCount} color="text-green-400"  />
          <StatPill icon={Activity}      label="Moderate" value={moderateCount}color="text-yellow-400" />
          <StatPill icon={AlertTriangle} label="Critical" value={criticalCount}color="text-red-400"    />
          {avgSoh && (
            <StatPill icon={Battery} label="Avg SOH" value={`${avgSoh}%`} color="text-purple-400" />
          )}
        </div>

        {/* ── Search + Filter Bar ── */}
        <div className="bg-white/[0.03] border border-white/10 rounded-2xl p-4 space-y-4">
          <div className="flex items-center gap-3 flex-wrap">
            {/* Search */}
            <div className="flex items-center gap-2 bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 flex-1 min-w-48">
              <Search size={15} className="text-gray-400 shrink-0" />
              <input
                type="text"
                placeholder="Search by name, battery ID, or model..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="bg-transparent border-none focus:outline-none text-sm text-white placeholder-gray-500 w-full"
              />
              {searchQuery && (
                <button onClick={() => setSearchQuery('')} className="text-gray-500 hover:text-white">
                  <X size={13} />
                </button>
              )}
            </div>

            {/* Filter Toggle */}
            <button
              onClick={() => setShowFilters(!showFilters)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl border transition text-sm font-medium
                ${showFilters
                  ? 'bg-cyan-500/20 border-cyan-500/30 text-cyan-400'
                  : 'bg-white/5 border-white/10 text-gray-400 hover:text-white hover:bg-white/10'}`}
            >
              <SlidersHorizontal size={15} />
              Filters
              {(filterModel !== 'all' || filterHealth !== 'all') && (
                <span className="w-5 h-5 bg-cyan-500 rounded-full text-[9px] font-bold text-black flex items-center justify-center">
                  {(filterModel !== 'all' ? 1 : 0) + (filterHealth !== 'all' ? 1 : 0)}
                </span>
              )}
            </button>

            {/* Sort */}
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value)}
              className="bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-cyan-500/50 transition"
            >
              <option value="date_desc">Newest First</option>
              <option value="date_asc">Oldest First</option>
              <option value="soh_desc">SOH: High → Low</option>
              <option value="soh_asc">SOH: Low → High</option>
              <option value="rul_desc">RUL: High → Low</option>
            </select>
          </div>

          {/* Expanded Filters */}
          {showFilters && (
            <div className="flex flex-wrap gap-4 pt-2 border-t border-white/5">
              {/* Model Filter */}
              <div className="flex-1 min-w-48">
                <p className="text-gray-500 text-[10px] uppercase font-bold mb-2">ML Model</p>
                <div className="flex flex-wrap gap-2">
                  {[
                    { value: 'all',             label: 'All Models' },
                    { value: 'random_forest',   label: '🌲 Random Forest' },
                    { value: 'svr',             label: '📐 SVR' },
                    { value: 'naive_bayes',     label: '📊 Naive Bayes' },
                    { value: 'gru_randomforest',label: '🔀 GRU+RF' },
                    { value: 'lstm_transformer',label: '🤖 LSTM' },
                  ].map(({ value, label }) => (
                    <button
                      key={value}
                      onClick={() => setFilterModel(value)}
                      className={`px-3 py-1.5 rounded-lg text-xs font-medium transition border
                        ${filterModel === value
                          ? 'bg-cyan-500/20 border-cyan-500/30 text-cyan-400'
                          : 'bg-white/5 border-white/10 text-gray-400 hover:text-white hover:bg-white/10'}`}
                    >
                      {label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Health Filter */}
              <div>
                <p className="text-gray-500 text-[10px] uppercase font-bold mb-2">Health Status</p>
                <div className="flex flex-wrap gap-2">
                  {[
                    { value: 'all',      label: 'All',      color: 'text-gray-400'   },
                    { value: 'healthy',  label: '✅ Healthy', color: 'text-green-400' },
                    { value: 'moderate', label: '⚠️ Moderate',color: 'text-yellow-400'},
                    { value: 'critical', label: '🔴 Critical',color: 'text-red-400'  },
                  ].map(({ value, label, color }) => (
                    <button
                      key={value}
                      onClick={() => setFilterHealth(value)}
                      className={`px-3 py-1.5 rounded-lg text-xs font-medium transition border
                        ${filterHealth === value
                          ? `bg-white/10 border-white/20 ${color}`
                          : 'bg-white/5 border-white/10 text-gray-400 hover:text-white hover:bg-white/10'}`}
                    >
                      {label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Clear Filters */}
              {(filterModel !== 'all' || filterHealth !== 'all') && (
                <button
                  onClick={() => { setFilterModel('all'); setFilterHealth('all'); }}
                  className="self-end text-xs text-gray-500 hover:text-white flex items-center gap-1 transition"
                >
                  <X size={12} /> Clear filters
                </button>
              )}
            </div>
          )}
        </div>

        {/* ── Results Count ── */}
        <div className="flex items-center justify-between text-xs text-gray-500">
          <span>
            Showing {paginated.length} of {processed.length} results
            {(searchQuery || filterModel !== 'all' || filterHealth !== 'all') && ' (filtered)'}
          </span>
          {processed.length !== totalCount && (
            <button
              onClick={() => { setSearchQuery(''); setFilterModel('all'); setFilterHealth('all'); }}
              className="text-cyan-400 hover:underline"
            >
              Show all {totalCount}
            </button>
          )}
        </div>

        {/* ── Log List ── */}
        {loading ? (
          <LoadingSkeleton />
        ) : error ? (
          <div className="flex flex-col items-center justify-center py-20 gap-4">
            <AlertTriangle size={48} className="text-red-400" />
            <p className="text-red-400 font-semibold">{error}</p>
            <button
              onClick={fetchHistory}
              className="px-5 py-2.5 bg-red-500/20 border border-red-500/30 text-red-400 rounded-xl text-sm hover:bg-red-500/30 transition"
            >
              Try Again
            </button>
          </div>
        ) : paginated.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 gap-4">
            <div className="w-16 h-16 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center">
              <HistoryIcon size={28} className="text-gray-600" />
            </div>
            <p className="text-gray-400 text-lg font-semibold">
              {searchQuery || filterModel !== 'all' || filterHealth !== 'all'
                ? 'No results match your filters'
                : 'No prediction history yet'}
            </p>
            <p className="text-gray-600 text-sm text-center max-w-xs">
              {searchQuery || filterModel !== 'all' || filterHealth !== 'all'
                ? 'Try adjusting your search or filters.'
                : 'Make a prediction to see your history here.'}
            </p>
            <button
              onClick={() => navigate('/prediction')}
              className="px-5 py-2.5 bg-gradient-to-r from-cyan-500 to-emerald-500 text-black font-bold rounded-xl text-sm hover:brightness-110 transition"
            >
              Make a Prediction
            </button>
          </div>
        ) : (
          <div className="space-y-3">
            {paginated.map((log, i) => {
              const soh    = parseFloat(log.soh_predicted) || 0;
              const rul    = parseFloat(log.rul_predicted)  || 0;
              const status = getHealthStatus(soh);
              const model  = MODEL_LABELS[log.report_type] || log.report_type || 'Unknown';

              return (
                <div
                  key={log.id ?? i}
                  className="bg-white/[0.03] border border-white/10 rounded-2xl px-5 py-4 flex items-center gap-5 hover:bg-white/[0.06] hover:border-white/20 transition group"
                >
                  {/* Status dot */}
                  <div className={`w-2.5 h-2.5 rounded-full shrink-0 ${status.dot}`} />

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="text-sm font-semibold text-white truncate">
                        {log.report_name || `Log #${(currentPage - 1) * ITEMS_PER_PAGE + i + 1}`}
                      </p>
                      {log.battery_id && (
                        <span className="text-[10px] text-cyan-600 bg-cyan-500/10 px-2 py-0.5 rounded-full border border-cyan-500/20">
                          {log.battery_id}
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-3 mt-1 flex-wrap">
                      <span className="text-[11px] text-gray-500 bg-white/5 px-2 py-0.5 rounded-md">
                        {model}
                      </span>
                      <span className="flex items-center gap-1 text-[11px] text-gray-600">
                        <Calendar size={10} />
                        {formatDate(log.created_at)}
                      </span>
                      <span className="flex items-center gap-1 text-[11px] text-gray-600">
                        <Clock size={10} />
                        {getTimeAgo(log.created_at)}
                      </span>
                    </div>
                  </div>

                  {/* SOH bar + value */}
                  <div className="hidden md:block w-28 shrink-0">
                    <div className="flex justify-between text-[10px] mb-1">
                      <span className="text-gray-500">SOH</span>
                      <span className={`font-bold ${status.color}`}>{soh.toFixed(1)}%</span>
                    </div>
                    <div className="w-full bg-white/5 rounded-full h-1.5">
                      <div
                        className={`h-1.5 rounded-full ${status.bar} transition-all duration-500`}
                        style={{ width: `${Math.min(soh, 100)}%` }}
                      />
                    </div>
                  </div>

                  {/* SOH value (mobile) */}
                  <div className="md:hidden text-right shrink-0">
                    <p className={`text-sm font-bold ${status.color}`}>{soh.toFixed(1)}%</p>
                    <p className="text-[10px] text-gray-500">SOH</p>
                  </div>

                  {/* RUL */}
                  <div className="text-right shrink-0 w-16">
                    <p className="text-sm font-bold text-cyan-400">{Math.round(rul)}</p>
                    <p className="text-[10px] text-gray-500">RUL cyc</p>
                  </div>

                  {/* Status badge */}
                  <span className={`hidden lg:inline-block px-3 py-1 rounded-full text-[10px] font-bold border shrink-0 ${status.bg} ${status.color} ${status.border}`}>
                    {log.health_status || status.label}
                  </span>

                  {/* Actions */}
                  <div className="flex items-center gap-2 shrink-0 opacity-0 group-hover:opacity-100 transition">
                    <button
                      onClick={() => setSelectedLog(log)}
                      className="p-2 bg-blue-500/20 text-blue-400 rounded-lg hover:bg-blue-500/30 transition"
                      title="View details"
                    >
                      <Eye size={14} />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* ── Pagination ── */}
        {totalPages > 1 && (
          <div className="flex items-center justify-center gap-2 pt-2">
            <button
              onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
              disabled={currentPage === 1}
              className="px-4 py-2 bg-white/5 border border-white/10 text-gray-400 rounded-xl text-sm hover:bg-white/10 transition disabled:opacity-30 disabled:cursor-not-allowed"
            >
              Previous
            </button>

            <div className="flex items-center gap-1">
              {[...Array(totalPages)].map((_, i) => {
                const page = i + 1;
                const isActive = page === currentPage;
                if (totalPages > 7 && Math.abs(page - currentPage) > 2 && page !== 1 && page !== totalPages) {
                  if (page === 2 || page === totalPages - 1) return <span key={i} className="text-gray-600 px-1">…</span>;
                  return null;
                }
                return (
                  <button
                    key={i}
                    onClick={() => setCurrentPage(page)}
                    className={`w-9 h-9 rounded-xl text-sm font-medium transition border
                      ${isActive
                        ? 'bg-cyan-500/20 border-cyan-500/30 text-cyan-400'
                        : 'bg-white/5 border-white/10 text-gray-400 hover:bg-white/10 hover:text-white'}`}
                  >
                    {page}
                  </button>
                );
              })}
            </div>

            <button
              onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
              disabled={currentPage === totalPages}
              className="px-4 py-2 bg-white/5 border border-white/10 text-gray-400 rounded-xl text-sm hover:bg-white/10 transition disabled:opacity-30 disabled:cursor-not-allowed"
            >
              Next
            </button>
          </div>
        )}

      </main>

      {/* ── Detail Modal ── */}
      {selectedLog && (
        <DetailModal log={selectedLog} onClose={() => setSelectedLog(null)} />
      )}
    </div>
  );
}